# Quadratures
In this chapter, we see how to find a definite integral numerically.

## Motivation
Consider a continuous function $f(x)$ in an interval $[a,b]$. We are interested in finding the integral $\int_a^b f(x)\, dx$. 

If we don't know $f(x)$ at all points, then how to find integral? Based on what we have studied till now, one way we can think of to approximate the integral is to first find a polynomial interpolant $p(x)$ using the known points and then find the integral $\int_a^b p(x) \, dx$. We can say that 
\begin{equation}
\int_a^b f(x)\, dx \approx \int_a^b p(x) \, dx
\end{equation}

But we have seen that there are issues like non-uniform convergence based in node distribution in the previous chapter. Therefore, we avoid this method. We resort to other methods to find the definite integral numerically.

Now, even if we know the exact form of the function at all points in the interval $(a,b)$, we can not always find a closed form for the anti-derivative of the function. 

Example:- Consider $f(x) = \exp(-x^2)$. We can't find the exact form of $\int f(x)\, dx = \int e^{-x^2}\, dx$. We can find $\int_{-\infty}^{\infty} e^{-x^2}\, dx$ using multivariable calculus methods say exactly. But for some random finite interval $(a,b)$, it is impossible to find the exact value. To get the approximate value, we use numerical methods. 

In some cases, though finding exact value of the integral is possible, it is extremely difficult to find it. 


## Different Schemes

### Basic Schemes

**ATTACH FIGURES FOR EACH SCHEME**

1. Lower/Left Riemann Sum:

\begin{equation}
\int_a^b f(x) \, dx \approx \sum_{i=0}^{n-1} f(x_i) \left( \frac{b-a}{n} \right)
\end{equation}

2. Upper/Right Riemann Sum:

\begin{equation}
\int_a^b f(x) \, dx \approx \sum_{i=1}^{n} f(x_i) \left( \frac{b-a}{n} \right)
\end{equation}

3. Trapezoidal Rule:
Instead of rectangles, let us approximate the areas by first dividing into trapeziums and summing up areas. 

\begin{equation}
\int_a^b f(x) \, dx \approx \frac{1}{2} h \left[ \sum_{i=1}^n (f(x_{i-1})+f(x_i)) \right]
\end{equation}

We can see that the trapezoidal rule is an average of Left and Right Riemann Sums.

4. Midpoint/Rectangular rule

\begin{equation}
\int_a^b f(x) \, dx \approx h \sum_{i=0}^{n-1} f\left( \frac{x_i+x_{i+1}}{2} \right) 
\end{equation}

### Accuracy of these schemes
Now the question arises - How accurate are these approximations? We'll estimate how accurate are the integrals in each sub-interval $\int_{x_i}^{x_{i+1}} f(x)\, dx$.

#### Midpoint Rule

Let $h_i = |x_{i+1}-x_i|$ and $y_i = (x_i+x_{i+1})/2$ for $i\in \{0,\dots,n-1\}$.

The Taylor's expansion of $f(x)$ about $x = y_i$ is:
\begin{align*}
f(x) &= f(y_i) + (x-y_i) f'(y_i) + \frac{(x-y_i)^2}{2!} f''(y_i) + \frac{(x-y_i)^3}{3!} f^{(3)}(y_i)+ \frac{(x-y_i)^4}{4!} f^{(4)}(y_i)\\
&+ \frac{(x-y_i)^5}{5!} f^{(5)}(y_i)+ \frac{(x-y_i)^6}{6!} f^{(6)}(\zeta_i)
\end{align*}
where $\zeta_i \in [x_i,x_{i+1}]$. Now we integrate the above equation on both sides from $x_{i}$ to $x_{i+1}$. Observe that,

\begin{align*}
\int_{x_i}^{x_{i+1}} (x-y_i)^{2k+1}\, dx &= \int_{x_i-y_i}^{x_{i+1}-y_i}t^{2k+1}\, dt & (t= x - y_i)\\
 &= \int_{-h_i/2}^{h_i/2}t^{2k+1}\, dt = 0  &
\end{align*}

\begin{align*}
\int_{x_i}^{x_{i+1}} (x-y_i)^{2k}\, dx &= \int_{-h_i/2}^{h_i/2}t^{2k}\, dt & (t= x - y_i)\\
 &= \dfrac{h_i^{2k+1}}{2^{2k}(2k+1)} &
\end{align*}

Therefore, 

$$\int_{x_i}^{x_{i+1}} f(x)\, dx = h_i f(y_i) + \frac{h_i^3}{24}f''(y_i)+\frac{h_i^5}{1920}f^{(4)}(y_i)+ \mathcal{O}(h_i^6)$$
and thus, error on a single panel caused by midpoint rule quadrature is given by:
\begin{equation}
\label{eq: midpoint step integral}
\int_{x_i}^{x_{i+1}} f(x)\, dx - h_i f(y_i) =  \frac{h_i^3}{24}f''(y_i)+\frac{h_i^5}{1920}f^{(4)}(y_i)+ \mathcal{O}(h_i^6)
\end{equation}
In other words, for each integral over a sub-interval $[x_i,x_{i+1}]$, midpoint rule is $\mathcal{O}(h_i^3)$ accurate.

To estimate the error in evaluating $$I = \int_a^b f(x) \, dx = \sum_{i = 0}^{n-1} \int_{x_i}^{x_{i+1}} f(x)\, dx,$$ we find the sum of errors in each of the $n$ integrals. Now, let's make a simplifying assumption. Assume that the interval $[a,b]$ is divided into $n$ equal sub-intervals of length $h = (b-a)/n$. Thus, 
$$I = \sum_{i=0}^{n-1} \left[ h f(y_i) + \frac{h^3}{24} f''(y_i) + \frac{h^5}{1920} f^{(4)}(y_i) + \mathcal{O}(h^6) \right]$$
$$\implies I = h\sum_{i=0}^{n-1} f(y_i)+ \frac{h^3}{24} \sum_{i=0}^{n-1}f''(y_i) + \frac{h^5}{1920}\sum_{i=0}^{n-1}f^{(4)}(y_i) + \mathcal{O}(nh^6)$$
$$\implies \int_{a}^b f(x)\, dx - h\sum_{i=0}^{n-1} f(y_i) = \frac{h^3}{24} n f''(z) + \mathcal{O}(nh^5)$$
where $$f''(z) = \frac{\sum_{i=0}^{n-1}f''(y_i)}{n}$$ and $z\in[a,b]$. Note that existence of such a $z$ can be shown using the intermediate value theorem. Also, as $nh = b-a$, we can say that

<!-- $$\text{Error} = \int_{a}^b f(x)\, dx - h\sum_{i=0}^{n-1} f(y_i) = \frac{h^2}{24} (b-a) f''(z) + \mathcal{O}[(b-a)h^4]$$ -->
\begin{equation}
\text{Error} = \int_{a}^b f(x)\, dx - h\sum_{i=0}^{n-1} f(y_i) = \frac{h^2}{24} (b-a) f''(z) + \mathcal{O}[(b-a)h^4]
\end{equation}

#### Trapezoidal Rule

We have from equation\ref{eq: midpoint step integral}

$$\int_{x_i}^{x_{i+1}} f(x)\, dx = h_i f(y_i) + \frac{h_i^3}{24}f''(y_i)+\frac{h_i^5}{1920}f^{(4)}(y_i)+ \text{H.O.T},$$
and the Taylor's expansion of $f(x)$ about $y_i$:
$$f(x) = f(y_i) +(x-y_i)f(y_i) + \frac{(x-y_i)^2}{2!} f''(y_i) + \frac{(x-y_i)^3}{3!} f^{(3)}(y_i)+ \frac{(x-y_i)^4}{4!} f^{(4)}(\xi_i).$$
On substituting $x_i$ and $x_{i+1}$ in the above equation and using the fact that $y_i-x_{i} = h_i/2 = x_{i+1}-y_i$, we obtain:
$$\frac{f(x_i)+f(x_{i+1})}{2} = f(y_i)+\frac{h_i^2}{8}f''(y_i)+ \mathcal{O}(h_i^4).$$
Thus,
\begin{align*}
\int_{x_i}^{x_{i+1}} f(x)\,dx- h_i \frac{f(x_i)+f(x_{i+1})}{2} &= \left[h_if(y_i)+\frac{h_i^3}{24}f''(y_i) +\mathcal{O}(h_i^5)\right] \\
&- h_i\left[f(y_i)+\frac{h_i^2}{8}f''(y_i) +\mathcal{O}(h_i^4)\right].
\end{align*}
<!-- $$\int_{x_i}^{x_{i+1}} f(x)\,dx- h_i \frac{f(x_i)+f(x_{i+1})}{2} = \left[h_if(y_i)+\frac{h_i^3}{24}f''(y_i) +\mathcal{O}(h_i^5)\right] - h_i\left[f(y_i)+\frac{h_i^2}{8}f''(y_i) +\mathcal{O}(h_i^4)\right].$$ -->
$$\implies \int_{x_i}^{x_{i+1}} f(x)\,dx- h_i \frac{f(x_i)+f(x_{i+1})}{2} = -\frac{h_i^3}{12}f''(y_i)+\mathcal{O}(h_i^5)$$
Following the same assumptions as stated for calculating error in midpoint rule quadrature *i.e.,* $h_i = h = (b-a)/n$, we can find out the error in estimating the integral $\int_a^b f(x)\, dx$ to be:
$$ \int_{a}^b f(x)\, dx - h\sum_{i=0}^{n-1}\frac{f(x_i)+f(x_{i+1})}{2} = -\frac{h^3}{12} n f''(z) + \mathcal{O}(nh^5),$$
where $$f''(z) = \frac{\sum_{i=0}^{n-1}f''(y_i)}{n},$$ and $z\in[a,b]$ (from Intermediate Value Theorem). Thus, 
\begin{equation}
\text{Error} = \int_{a}^b f(x)\, dx - h\sum_{i=0}^{n-1} \frac{f(x_i)+f(x_{i+1})}{2} = -\frac{(b-a)h^2}{12}f''(z) + \mathcal{O}[(b-a)h^4]
\end{equation}


### Simpson's Rule

Recall that the errors in estimating the integral $\int_a^b f(x)\, dx$  using 
\begin{align}
\text{Midpoint rule} &= \frac{(b-a)h^2}{24}f''(z)+\mathcal{O}(h^4)\\
\text{Trapezoidal rule} &= -\frac{(b-a)h^2}{12}f''(z) + \mathcal{O}(h^4)
\end{align}

Thus, these quadratures are 2nd order accurate methods. Now, next question arises. Can we do better? The answer turns out to be yes. Let $R(f)$ and $T(f)$ be the estimates of the integral $\int_a^b f(x)\, dx$ using rectangular (midpoint) rule and Trapezoidal rule respectively *i.e.,*

\begin{align}
R(f) &= \sum_{i=0}^{n-1}hf(y_i)\\
T(f) &= \sum_{i=0}^{n-1}\frac{h}{2}[f(x_i)+f(x_{i+1})]
\end{align}

Now, consider the approximation
$$\int_a^b f(x)\, dx  \approx \frac{2R(f) + T(f)}{3}.$$
The error caused by this approximation is:
$$ \int_a^bf(x)\, dx - \frac{2R(f) + T(f)}{3} = \frac{1}{3} \left(\frac{2}{24}-\frac{1}{12} \right) (b-a)h^2f''(z) + \mathcal{O}(h^4) = \mathcal{O}(h^4).$$

Therefore, the quadrature:
\begin{equation}
\int_a^b f(x)\, dx  \approx \frac{2R(f) + T(f)}{3} = h\sum_{i=0}^{n-1}\frac{4f(y_i)+f(x_i)+f(x_{i+1})}{6},
\end{equation}
is 4th order accurate. This is known as the **Simpson's rule**.


### Trapezoidal Rule with End point Corrections

Let's rewrite Simpson's rule for quadrature as follows:
$$\int_a^b f(x)\, dx  \approx \frac{2}{3}h \sum_{i=0}^{n-1}f(y_i)+\frac{h}{6}[f(x_0)+f(x_n)]+\frac{h}{3}\sum_{i=1}^{n-1}f(x_i)$$

Therefore, we can observe that Simpson's rule requires $(2n+1)$ function evaluations. Now, can we develop a scheme which is of the same order as that of the Simpson's rule but has lesser function evaluations? To do this, let us revisit Trapezoidal rule. 

The integral $\int_{x_i}^{x_{i+1}}f(x)\, dx$ is found out to be
$$\int_{x_i}^{x_{i+1}} f(x)\,dx = h \frac{f(x_i)+f(x_{i+1})}{2}  -\frac{h^3}{12}f''(y_i)+\mathcal{O}(h^5)$$
To estimate $f''(y_i)$, we use Taylor series of $f'(x)$ about $y_i$ for $x=x_i$ and $x=x_{i+1}$.

<!-- $$f'(x_i) = f'(y_i) + (x_i-y_i)f''(y_i)+ \frac{(x_i-y_i)^2}{2!}f'''(y_i) + \frac{(x_i-y_i)^3}{3!}f^{(4)}(y_i) + \frac{(x_i-y_i)^4}{4!}f^{(5)}(y_i)+ \text{H.O.T}$$ -->
<!-- $$f'(x_{i+1}) = f'(y_i) + (x_{i+1}-y_i)f''(y_i)+ \frac{(x_{i+1}-y_i)^2}{2!}f'''(y_i) + \frac{(x_{i+1}-y_i)^3}{3!}f^{(4)}(y_i) + \frac{(x_{i+1}-y_i)^4}{4!}f^{(5)}(y_i)+ \text{H.O.T}$$ -->
\begin{align*}
f'(x_i) &= f'(y_i) + (x_i-y_i)f''(y_i)+ \frac{(x_i-y_i)^2}{2!}f'''(y_i) \\
        &+\frac{(x_i-y_i)^3}{3!}f^{(4)}(y_i) + \frac{(x_i-y_i)^4}{4!}f^{(5)}(y_i)+ \text{H.O.T}\\
f'(x_{i+1}) &= f'(y_i) + (x_{i+1}-y_i)f''(y_i)+ \frac{(x_{i+1}-y_i)^2}{2!}f'''(y_i) \\
            &+\frac{(x_{i+1}-y_i)^3}{3!}f^{(4)}(y_i) + \frac{(x_{i+1}-y_i)^4}{4!}f^{(5)}(y_i) + \text{H.O.T}        
\end{align*}

Using the fact that $y_i - x_i = h/2 = x_{i+1}-y_i$, we can see that:
$$f'(x_{i+1})-f'(x_i) = hf''(y_i) + \frac{h^3}{24}f^{(4)}(y_i)+\text{H.O.T}$$
$$\implies f''(y_i) = \frac{f'(x_{i+1})-f'(x_i)}{h}-\frac{h^2}{24}f^{(4)}(y_i)+ \text{H.O.T}$$
Thus, on subtituting the value of $f''(y_i)$ in the panel integral, we get:
$$\int_{x_i}^{x_{i+1}} f(x)\, dx = h \frac{f(x_i)+f(x_{i+1})}{2}  -\frac{h^2}{12}[f'(x_{i+1})-f'(x_i)]+\mathcal{O}(h^5).$$
We now find $\int_a^b f(x)\, dx$ by summing the panel integrals $\int_{x_i}^{x_{i+1}}f(x)\, dx$ from $i=0$ to $i=n-1$ and using the information that $x_0 = a$, $x_n = b$ and $nh = b-a$, we can find out that the integral to be:

\begin{equation}
\int_a^b f(x)\, dx = \frac{h}{2}\sum_{i=0}^{n-1}[f(x_i)+f(x_{i+1})] - \frac{h^2}{12}[f'(b)-f'(a)]+\mathcal{O}(h^4).
\end{equation}

This quadrature is referred to as **Modified Trapezoidal rule** or **Trapezoidal rule with end point corrections**. We can observe that

1. This quadrature requires $n+3$ function evaluations (More precisely, $n+1$ function evaluations & 2 derivative evaluations) which is lesser compared to that of Simpson's rule. Thus, we have achieved a quadrature having same order of accuracy but requiring smaller computational cost.

2. To estimate integral using this method, we need to have access to the derivative of the function only at the end points but not any intermediate points between $x=a$ and $x=b$.

Similarly one can write a **Rectangular (Mid point) rule with end point corrections** as:
\begin{equation}
\int_a^b f(x)\, dx = h\sum_{i=0}^{n-1}f\left(\frac{x_i+x_{i+1}}{2}\right) + \frac{h^2}{24}[f'(b)-f'(a)]+\mathcal{O}(h^4).
\end{equation}


## Euler-Maclaurian Formula

Now, if we have access to higher derivatives at the end points then can we get more accurate quadratures? We shall answer this question in this section.

### Introduction

### Formula and Derivation

The Euler-Maclaurin summation is as follows: 

Let $p\in \mathbb{N}$. If $f \in C^{2p}([a, b])$, we then have,
\begin{equation}
\sum_{n=a}^b f(n) = \int_a^bf(x)\, dx+\frac{f(a)+f(b)}{2}+\sum_{k=1}^p \frac{b_{2k}}{(2k)!}[f^{(2k-1)}(b) - f^{(2k-1)}(a)]-\int_a^b \frac{B_{2p}(\{t\})}{(2p)!}f^{(2p)}(t) \, dt
\end{equation}
where $B_k(x)$ are the Bernoulli polynomials of degree $k$, $b_k = B_k(0)$ are the Bernoulli numbers and $\{t\}\in[0,1)$ is fractional part of t.

**Bernoulli Polynomial:** The Bernoulli polynomials $\{B_k(x)\}_{k\geq 0}$ are defined as:
\begin{align}
B_0(x) &= 1\\
B_k'(x) &= kB_{k-1}(x)\\
\int_0^1 B_k(x)\, dx &= 1 \ \ \ \forall k\geq 1
\end{align}
First few Bernoulli polynomials are: $$\{ 1, x-\frac{1}{2}, x^2-x+\frac{1}{6}, x^3-\frac{3}{2}x^2+\frac{1}{2}x, \dots \},$$
and hence corresponding Bernoulli numbers are $$\{1,-\frac{1}{2},\frac{1}{6},0,\dots\}.$$

**Proof of Euler-Maclaurian formula**

We shall prove this by induction. 

*Base Case* ($p=1$)

We need to show that: $$ \sum_{n=a}^b f(n) = \int_a^b f(x)\, dx + \frac{f(a)+f(b)}{2}+ \frac{b_2}{2!}[f'(b)-f'(a)]-\int_a^b \frac{B_2(\{t\})}{2!}f''(t)\, dt,$$ or in other words $$ \int_a^b \frac{B_2(\{t\})}{2!}f''(t)\, dt =  \int_a^b f(x)\, dx + \frac{f(a)+f(b)}{2}+ \frac{b_2}{2!}[f'(b)-f'(a)]-\sum_{n=a}^b f(n) .$$

We first split the integral into sum of integral over panels.
$$\int_a^b \frac{B_2(\{t\})}{2!}f''(t)\, dt = \frac{1}{2} \sum_{n=a}^{b-1}\int_{n}^{n+1}B_2(\{t\})\,d(f'(t)).$$ Now let us consider each panel integral.
$$\int_{n}^{n+1}B_2(\{t\})d(f'(t)) = \int_{n}^{n+1} \left(\{t\}^2-\{t\}+\frac{1}{6} \right)\, d(f'(t))$$
$$ =\int_{n}^{n+1} \left[(t-n)^2-(t-n)+\frac{1}{6} \right]\, d(f'(t)) $$
$$ = \left[f'(t)\left((t-n)^2-(t-n)+\frac{1}{6}\right) \right]_{n}^{n+1}-\int_{n}^{n+1}(2(t-n)-1)f'(t)\, dt$$
$$ = \frac{1}{6}[f'(n+1)-f'(n)] - \int_n^{n+1}f'(t) (2t-2n-1)\, dt$$

$$\int_n^{n+1}f'(t) (2t-2n-1)\, dt = \left[(2t-2n-1) f(t) \right]_n^{n+1}-\int_n^{n+1}2f(t)\, dt$$
$$=f(n+1)+f(n)-2\int_n^{n+1}f(t)\, dt$$

$$\implies \int_{n}^{n+1}B_2(\{t\})d(f'(t)) =\frac{1}{6}[f'(n+1)-f'(n)] -f(n+1)-f(n)+2\int_n^{n+1}f(t)\, dt$$
$$\implies \sum_{n=a}^{b-1}\int_{n}^{n+1}B_2(\{t\})d(f'(t)) = \frac{1}{6}[f'(b)-f'(a)] -\sum_{n=a}^{b-1}[f(n+1)+f(n)]+2\int_a^{b}f(t)\, dt $$

$$\implies \int_a^b B_2(\{t\})f''(t)\, dt = \frac{1}{6}[f'(b)-f'(a)] -2\sum_{n=a}^b f(n) + f(a) + f(b)+2\int_a^b f(t)\, dt$$
$$\implies \int_a^b \frac{B_2(\{t\})}{2!}f''(t)\, dt = \frac{1}{12}[f'(b)-f'(a)] -\sum_{n=a}^b f(n) +\frac{f(a)+f(b)}{2}+\int_a^b f(t)\, dt.$$
Since $b_2 = 1/6$, we can rewrite the above expression as:
$$\frac{B_2(\{t\})}{2!}f''(t)\, dt = \int_a^b f(t)\, dt+\frac{f(a)+f(b)}{2}+\frac{b_2}{2}[f'(b)-f'(a)]  -\sum_{n=a}^b f(n).$$


*Inductive step* (Assume that the formula is true for some $p$, then the formula is true for $p+1$)

We assume that for some $p \ge 1$, the Euler-Maclaurian summation is true.

$$\sum_{n=a}^b f(n) = \int_a^bf(x)\, dx+\frac{f(a)+f(b)}{2}+\sum_{k=1}^p \frac{b_{2k}}{(2k)!}(f^{(2k-1)}(b) - f^{(2k-1)}(a))-\int_a^b \frac{B_{2p}(\{t\})}{(2p)!}f^{(2p)}(t) \, dt$$

Now, we need to now prove that the above is true for $p+1$, i.e., we need to prove that

$$
\sum_{n=a}^{b} f(n)=\int_{a}^{b} f(x) d x+\frac{f(b)+f(a)}{2}+\sum_{k=1}^{p+1} \frac{b_{2 k}}{(2 k) !}\left(f^{(2 k-1)}(b)-f^{(2 k-1)}(a)\right)-\int_{a}^{b} \frac{B_{2(p+1)}(\{t\})}{(2(p+1)) !} f^{(2(p+1))}(t) \, dt
$$

Subtracting the above 2 equations, we can say that the inductive step is equivalent to proving:

\begin{equation}\label{eq: 1a final}
    \int_{a}^{b} \frac{B_{2(p+1)}(\{t\})}{(2(p+1)) !} f^{(2(p+1))}(t) d t=\int_{a}^{b} \frac{B_{2 p}(\{t\})}{(2 p) !} f^{(2 p)}(t) d t+\frac{b_{2(p+1)}}{(2(p+1)) !}\left(f^{(2 p+1)}(b)-f^{(2 p+1)}(a)\right)
\end{equation}

Define LHS of equation\eqref{eq: 1a final} as:
    $$I_{p+1} = \int_{a}^{b} \frac{B_{2(p+1)}(\{t\})}{(2(p+1)) !} f^{(2(p+1))}(t)\,  dt$$
    $$\implies I_{p+1} = \sum_{n=a}^{b-1} \int_{n}^{n+1} \frac{B_{2(p+1)}(\{t\})}{(2(p+1)) !} f^{(2(p+1))}(t) \, dt = \sum_{n=a}^{b-1} \int_{n}^{n+1} \frac{B_{2(p+1)}(t-n)}{(2(p+1)) !} f^{(2(p+1))}(t)\,  dt $$
    Define $$J_{n,p+1} = \int_{n}^{n+1} \frac{B_{2(p+1)}(t-n)}{(2(p+1)) !} f^{(2(p+1))}(t)\,  dt$$
    
 Integrating by-parts, we get:
    $$
\begin{aligned}
J_{n, p+1} & =\left[B_{2(p+1)}(t-n) f^{(2 p+1)}(t)\right]_{n} ^{n+1}-\int_{n}^{n+1} B'_{2(p+1)}(t-n) f^{(2 p+1)}(t) d t \\
\implies J_{n, p+1} & =B_{2(p+1)}(1) f^{(2 p+1)}(n+1)-B_{2(p+1)}(0) f^{(2 p+1)}(n)-\int_{n}^{n+1} 2(p+1) B_{2 p+1}(t-n) f^{(2 p+1)}(t) d t \\
\implies J_{n, p+1} & =b_{2(p+1)}\left(f^{(2 p+1)}(n+1)-f^{(2 p+1)}(n)\right)-2(p+1) \int_{n}^{n+1} B_{2 p+1}(t-n) f^{(2 p+1)}(t) d t \\
\implies J_{n, p+1} & =b_{2(p+1)}\left(f^{(2 p+1)}(n+1)-f^{(2 p+1)}(n)\right)\\&-2(p+1)\left(\left[B_{2 p+1}(t-n) f^{(2p)}(t)\right]_{n} ^{n+1}-\int_{n}^{n+1} B'_{2 p+1}(t-n) f^{(2p)}(t) d t\right).
\end{aligned}
$$

As $B_k(0) = B_k(1)$ for $k\ge 2$, we have used $B_{2(p+1)}(1) = B_{2(p+1)}(0)$ for $p\ge 1$. 

Therefore, 
$$
\begin{aligned}
J_{n, p+1} & =b_{2(p+1)}\left(f^{(2 p+1)}(n+1)-f^{(2 p+1)}(n)\right)+2(p+1)\left(\int_{n}^{n+1} B'_{2 p+1}(t-n) f^{(2 m)}(t) d t\right) \\
\implies J_{n, p+1}& =b_{2(p+1)}\left(f^{(2 p+1)}(n+1)-f^{(2 p+1)}(n)\right)+2(p+1)\left(\int_{n}^{n+1}(2 p+1) B_{2 p}(t-n) f^{(2 p)}(t) d t\right) \\
\implies J_{n, p+1} & =b_{2(p+1)}\left(f^{(2 p+1)}(n+1)-f^{(2 p+1)}(n)\right)+2(p+1)(2 p+1) I_{n, p-1}
\end{aligned}
$$

Thus,

$$
\begin{aligned}
I_{p+1} & =\sum_{n=a}^{b-1} J_{n, p+1}=\sum_{n=a}^{b-1}\left(b_{2(p+1)}\left(f^{(2 p+1)}(n+1)-f^{(2 p+1)}(n)\right)+2(p+1)(2 p+1) J_{n, p-1}\right) \\
\implies I_{p+1} & =b_{2(p+1)} \sum_{n=a}^{b-1}\left(f^{(2 p+1)}(n+1)-f^{(2 p+1)}(n)\right)+(2 p+2)(2 p+1) \sum_{n=a}^{b-1} J_{n, p-1} \\
\implies I_{p+1} & =b_{2(p+1)}\left(f^{(2 p+1)}(b)-f^{(2 p+1)}(a)\right)+(2 p+2)(2 p+1) I_{p} \\
\implies \frac{I_{p+1}}{(2(p+1)) !} & =\frac{b_{2(p+1)}}{(2(p+1)) !}\left(f^{(2 p+1)}(b)-f^{(2 p+1)}(a)\right)+\frac{I_{p}}{(2 p) !}
\end{aligned}
$$

$$\implies \int_{a}^{b} \frac{B_{2(p+1)}(\{t\})}{(2(p+1)) !} f^{(2(p+1))}(t) d t =\int_{a}^{b} \frac{B_{2 p}(\{t\})}{(2 p) !} f^{(2 p)}(t) d t+\frac{b_{2(p+1)}}{(2(p+1)) !}\left(f^{(2 p+1)}(b)-f^{(2 p+1)}(a)\right)$$
which proves the inductive step for any $p\ge 1$

As the base case $p=1$ and inductive step are true, we can say that the given statement
is true according to principle of mathematical induction.

### Examples

Consider $f(x) = 1/x$ and $a=1$ and $b = m \in \{2,3\dots\}$. We substitute these in Euler-Maclaurian formula for $p=1$ to obtain the below expression:
$$\sum_{n=1}^m \frac{1}{n} = \ln m+\frac{1}{2}+\frac{1}{2m}+\frac{b_2}{2}\left( 1-\frac{1}{m^2}\right)-\int_1^m \frac{B_2(\{t\})}{t^3}\, dt.$$
The LHS is the $m^{\text{th}}$ Harmonic sum $H_m$. We'll now substitute the values of $b_2 = 1/6$ and $B_2(\{t\}) = \{t\}^2-\{t\}+1/6$ to estimate $H_m$.

$$H_m = \ln m + \frac{7}{12}+\frac{1}{2m}-\frac{1}{12m^2}-\int_1^m \frac{B_2(\{t\})}{t^3}\, dt.$$
$$\int_1^m \frac{B_2(\{t\})}{t^3}\, dt = \int_1^{\infty} \frac{B_2(\{t\})}{t^3}\, dt -\int_m^{\infty} \frac{B_2(\{t\})}{t^3}\, dt$$
As $\{t\}\in [0,1)$, we can observe that $0\leq |B(\{t\})| \leq 1/6$, and hence
$$0 \leq \Bigg|\int_m^{\infty} \frac{B_2(\{t\})}{t^3}\, dt\Bigg| \leq \Bigg|\int_m^{\infty} \frac{1}{6t^3}\, dt\Bigg|=\frac{1}{12m^2}.$$
This implies:
$$\Bigg| H_m -\ln m- \gamma -\frac{1}{12m} \Bigg| = \Bigg| \frac{1}{12m^2} + \int_m^{\infty} \frac{B_2(\{t\})}{t^3}\, dt \Bigg| \leq \frac{1}{6m^2},$$
where $$\gamma := \frac{7}{12} - \int_1^{\infty} \frac{B_2(\{t\})}{t^3}\,dt,$$ is the Euler-Mascheroni constant. Not many properties of this constant is known yet (*Eg:* Is $\gamma$ rational or irrational? Algebraic or transcendental?). Keeping aside these burning questions, we can thus say that:
\begin{equation}
H_m \approx \ln m+ \gamma +\frac{1}{12m} \ \ \text{; \ Error} = \frac{1}{6m^2}
\end{equation}
As an example, $H_{10^6} = \ln 10^6 + \gamma +1/(2\times 10^6)$ with an error of $1/(6\times 10^{12})$.

We can also derive Stirling's approximation using Euler-Maclaurian formula by taking 
$f(n) = \ln n$ to get $$\log(n!) = \log\left( \sqrt{2\pi n} \left(\frac{n}{e} \right)^n\right)+ \mathcal{O}\left( \frac{1}{n}\right)$$



### Higher Order Quadratures

Now that we have seen what Euler-Maclaurian formula is, now we'll come back to our question posed earlier in this section. Can we get more accurate quadratures if we know higher derivatives at the end-points. We can firstly see that:
$$\int_a^b f(x) \, dx = \sum_{k=0}^{n-1}\int_{x_k}^{x_{k+1}} f(x)\, dx$$
Each panel integral can be written as:
$$\int_{x_k}^{x_{k+1}} f(x)\, dx = \int_0^1 f(x_0+kh+\alpha h) h\, d\alpha = h \int_0^1 F(\alpha) \, d\alpha$$
where $x = x_k + \alpha h = x_0+kh+\alpha h$ and as $x \in [x_k,x_{k+1}]$, we have $\alpha \in [0,1]$ and $F(\alpha) = f(x_0+kh+\alpha h)$. Now, we use Euler-Maclaurian formula to evaluate $\int_0^1F(\alpha)\, d\alpha$.

$$\int_0^1F(\alpha)\, d\alpha = \sum_{n=0}^1 F(n) - \frac{F(0)+F(1)}{2}-\sum_{k=1}^p \frac{b_{2k}}{(2k)!}[F^{(2k-1)}(1)-F^{(2k-1)}(0)]+\int_0^1 \frac{B_{2p}(\{t\})}{(2p)!}F^{(2p)}\,dt$$
$$\implies \int_0^1F(\alpha)\, d\alpha =  \frac{F(0)+F(1)}{2}-\sum_{k=1}^p \frac{b_{2k}}{(2k)!}[F^{(2k-1)}(1)-F^{(2k-1)}(0)]+\int_0^1 \frac{B_{2p}(\{t\})}{(2p)!}F^{(2p)}(t)\,dt.$$
Let us now revert back from $F(\alpha)$ to $f(x)$. Note that as $F(\alpha) = f(x_0+kh+\alpha h)$, we have $F^{(m)}(\alpha) = h^m f^{(m)}(x_0+kh+\alpha h)$ for any $m\geq 1$. Thus,

$$\int_{0}^1 F(\alpha)\, d\alpha = \frac{f(x_k)+f(x_{k+1})}{2}-\sum_{l=1}^p \frac{b_{2l}}{(2l)!}h^{2l-1}[f^{(2l-1)}(x_{k+1})-f^{(2l-1)}(x_k)]+h^{2p} \tilde{R}_p,$$
where $$\tilde{R}_p := \int_0^1 \frac{B_{2p}(\{t\})}{(2p)!}f^{(2p)}(x_0+kh+th)\,dt.$$ Thus, integral over a panel would be $$\int_{x_{k}}^{x_{k+1}}f(x)\, dx = \alpha \int_0^1 F(\alpha)\, d\alpha$$
$$\int_{x_k}^{x_{k+1}}f(x)\, dx = \frac{h}{2}[f(x_k)+f(x_{k+1})]-\sum_{l=1}^p \frac{b_{2l}}{(2l)!}h^{2l}[f^{(2l-1)}(x_{k+1})-f^{(2l-1)}(x_k)]+h^{2p+1} \tilde{R}_p.$$
We sum up these panel integrals to get $\int_a^b f(x)\, dx$ as follows:
$$\int_a^b f(x)\, dx = \sum_{k=0}^{n-1}\int_{x_k}^{x_{k+1}} f(x)\, dx$$
$$\implies \int_a^b f(x)\, dx = \frac{h}{2}[f(x_0)+f(x_n)]+h\sum_{k=1}^{n-1}f(x_k) - \sum_{l=1}^p\frac{b_{2l}}{(2l)!}h^{2l}[f^{2l-1}(b)-f^{(2l-1)}(a)]+\mathcal{O}(h^{2p})$$
Substituting an appropriate value of $p$ gives a quadrature which is $\mathcal{O}(h^{2p})$ accurate. For example:

1. On substituting $p=1$, $p=2$, we get back trapezoidal rule and modified trapezoial rules respectively.

2. For $p=3$, we get a $\mathcal{O}(h^6)$ Trapezoidal rule as follows:
$$ \int_a^b f(x)\, dx = \frac{h}{2}[f(a)+f(b)] + h\sum_{i=1}^{n-1}f(x_i) -\frac{h^2}{12}[f'(b)-f'(a)]+\frac{h^4}{720}[f'''(b)-f'''(a)]+\mathcal{O}(h^6).$$



## Gaussian Quadratures


<!-- # Parts -->

<!-- You can add parts to organize one or more book chapters together. Parts can be inserted at the top of an .Rmd file, before the first-level chapter heading in that same file.  -->

<!-- Add a numbered part: `# (PART) Act one {-}` (followed by `# A chapter`) -->

<!-- Add an unnumbered part: `# (PART\*) Act one {-}` (followed by `# A chapter`) -->

<!-- Add an appendix as a special kind of un-numbered part: `# (APPENDIX) Other stuff {-}` (followed by `# A chapter`). Chapters in an appendix are prepended with letters instead of numbers. -->



