# Numerical Differentiation

## Motivation

Given a continuous function $f(x)$. We have seen that finding anti-derivative for all functions is not possible and hence, we resort to finding approximate values of definite integrals using Numerical methods(Quadratures). But derivatives can be found for any differentiable function $f(x)$ using Chain rule etc.,

Eg:-  Consider $f(x) = \cos(x^2)$ which is continuous and differentiable. 

$\int_0^1 f(x) \, dx = \int_0^1 \cos(x^2)\, dx$ has no closed form. But $f'(x) = -2x\sin(x^2)$ which can be found using chain rule. 

Now the question which naturally arises is: Why do we need to think of finding derivatives numerically then?

1. Consider the case where $f(x)$ is known at discrete node points $\{x_i\}_{i=0}^n$. To find derivatives at these nodes, one way is to interpolate using an interpolant polynomial $p(x)$ and then find $p'(x)$. We can find using a less computationally expensive way as will be discussed in this chapter.

2. Solving Differential Equations

    a. **Ordinary Differential Equations(ODEs):**
    
    **Simple Pendulum:-** 
    
    **ATTACH SIMPLE PENDULUM PIC WITH ITS FBD**
    
    For simple pendulum with no damping and using small angle approximation about equilibrium position, we have the equation of motion as:
    \begin{equation}
    \frac{d^2\theta}{dt^2}+\frac{g}{l}\theta = 0
    \end{equation}
    with initial conditions $\theta(t=0)= \theta_0$ and $\frac{d\theta}{dt}(t=0) = 0$.
    
    The exact solution for this ODE is known which is $\theta = \theta_0 \cos\left( \sqrt{g}{l} t \right)$. 
    
    But if the assumptions of small angle oscillations and no damping are relaxed then the equation of motion becomes:
    \begin{equation}
    \frac{d^2\theta}{dt^2}+C\frac{d\theta}{dt}+\frac{g}{l}\sin \theta = 0
    \end{equation}
    with initial conditions remaining the same. But solving this ODE analytically is impossible. Therefore, we need access to numerical methods to solve ODEs.
    
    b. **Partial Differential Equations(PDEs):-**
    
    Some examples are Wave Equation(Hyperbolic PDE) 
    $$\partial{\partial^2 u}{\partial t^2}-c^2 \nabla^2 u= 0$$
    
    Heat/Diffusion Equation(Parabolic PDE)
    $$\partial{\partial u}{\partial t}-\alpha \nabla^2 u= 0$$
    
    Laplace Equation(Elliptic PDE)
    $$\nabla^2 u = 0 \text{ on } \Omega$$
    with boundary condition $u = f(x,y,z)$ on $\partial \Omega$
    
    For specific boundaries like a rectangle, the solution can be found analytically. But for a general boundaries, it is extremely difficult to find analytical solutions. Therefore, numerical methods have to be used for solving these PDEs.
    
In this course, we consider solving only ODEs i.e, 1 independent variable per dependent variable. 

## Finite Differences

To construct approximations for derivatives, we use Taylor series. Let $f(t)$ be a real differentiable function whose values are known at $\{t_i\}_{i=0}^n=t_0+i h$ where $h = \Delta t$ which is a constant

Define $f_i = f(t_i)$ and $f'_i = \frac{df}{dt}(t_i)$

We can write $f_{j+1}$ in terms of $f_j$ and derivatives  of $f$ at $t_j$ by writing Taylor series of $f(t_{j+1})$ about $t=t_j$. 

$$f_{j+1} = f(t_j+h)= f(t_j)+hf'(t_j)+\frac{h^2}{2!}f''(t_j)+\dots$$
$$\dfrac{f_{j+1}-f_j}{h}-\frac{h}{2!}f''(t_j)-\frac{h^2}{3!}f'''(t_j)-\dots = f'(t_j) = f'_j$$

\begin{equation}
f'_j = \dfrac{f_{j+1}-f_j}{h} + \mathcal{O}(h)
\end{equation}
The above approximation is called **Forward Finite Difference Approximation**


Now consider the Taylor series of $f(t_{j-1})$ about $t=t_j$.

$$f_{j-1} = f(t_j-h)= f(t_j)-hf'(t_j)+\frac{h^2}{2!}f''(t_j)+\dots$$
$$\dfrac{f_{j}-f_{j-1}}{h}+\frac{h}{2!}f''(t_j)-\frac{h^2}{3!}f'''(t_j)+\dots = f'(t_j) = f'_j$$

\begin{equation}
f'_j = \dfrac{f_{j}-f_{j-1}}{h} + \mathcal{O}(h)
\end{equation}
The above approximation is called **Backward Finite Difference Approximation**

We can clearly see that both Forward and Backward Finite differences are **1st order accurate.** Now the question to ask is "Can we improve the order of accuracy?" 

Consider the Taylor Series Expansions of $f_{j+1}$ and $f_{j-1}$ about $t_j$. 
\begin{align*}
f_{j+1} &= f(t_j)+hf'(t_j)+\frac{h^2}{2!}f''(t_j)+\frac{h^3}{3!}f'''(t_j)+\frac{h^4}{4!}f^{(4)}(t_j)+\dots\\
f_{j-1} &= f(t_j)-hf'(t_j)+\frac{h^2}{2!}f''(t_j)-\frac{h^3}{3!}f'''(t_j)+\frac{h^4}{4!}f^{(4)}(t_j)-\dots
\end{align*}
Subtracting () from (), we get
$$\implies f_{j+1}-f_{j-1} = 2hf'_j+\frac{2h^3}{3!}f'''(t_j)+\frac{2h^5}{5!}f^{(5)}(t_j)+\dots$$
$$\implies f_{j+1}-f_{j-1}-\frac{2h^3}{3!}f'''(t_j)-\frac{2h^5}{5!}f^{(5)}(t_j)-\dots = 2hf'_j$$

\begin{equation}
f'_j = \frac{f_{j+1}-f_{j-1}}{2h} + \mathcal{O}(h^2)
\end{equation}
We can see that the order of accuracy has been improved to 2. This approximation is called **Central Finite Difference Approximation.**


**ATTACH CODE/ACCURACY PLOT**


To improve the order of accuracy, we need to consider more "grid points". To understand this clearly, let us consider the example below.

**Example:** Construct Finite difference scheme to find $f'_j$ from $f_j$, $f_{j\pm 1}$ and $f_{j \pm 2}$. 

**Solution:**

Let 
\begin{equation}
f'_j = a f_{j+2}+b f_{j+1}+cf_{j}+d f_{j-1}+e f_{j-2}
\end{equation}
where $a,b,c,d,e$ are to be found.

Write Taylor series of $f_{j \pm 1}$ and $f_{j\pm 1}$ about $t_j$ on RHS of the above equation(), we get:
\begin{align*}
f'_j  &= a\left(f(t_j)+2hf'(t_j)+\frac{(2h)^2}{2!}f''(t_j)+\frac{(2h)^3}{3!}f'''(t_j)+\frac{(2h)^4}{4!}f^{(4)}(t_j)+\frac{(2h)^5}{5!}f^{(5)}(t_j)+\dots \right) \\
&+ b \left( f(t_j)+hf'(t_j)+\frac{h^2}{2!}f''(t_j)+\frac{h^3}{3!}f'''(t_j)+\frac{h^4}{4!}f^{(4)}(t_j)+\frac{h^5}{5!}f^{(5)}(t_j)+\dots \right)\\
&+ cf_j \\
&+ d \left(f(t_j)-hf'(t_j)+\frac{h^2}{2!}f''(t_j)-\frac{h^3}{3!}f'''(t_j)+\frac{h^4}{4!}f^{(4)}(t_j)-\frac{h^5}{5!}f^{(5)}(t_j)+\dots \right)\\
&+ e \left( f(t_j)-2hf'(t_j)+\frac{(2h)^2}{2!}f''(t_j)-\frac{(2h)^3}{3!}f'''(t_j)+\frac{(2h)^4}{4!}f^{(4)}(t_j)-\frac{(2h)^5}{5!}f^{(5)}(t_j)+\dots \right)
\end{align*}

\begin{align*}
\implies f'_j  &= (a+b+c+d+e) f_j + h(2a+b-d-2e)f'_j+ \frac{h^2}{2!}(4a+b+d+4e) f''_j \\
&+ \frac{h^3}{3!}(8a+b-d-8e) f'''_j + \frac{h^4}{4!}(16a+b+d+16e) f^{(4)}_j\\
&+ \frac{h^5}{5!}(32a+b-d-32e) f^{(5)}_j+\mathcal{O}(h^6)
\end{align*}
Now there are 5 variables but infinitely many equations(obtained after comparing coefficients of $f$ and its derivatives at $t_j$ on both sides of the above equation).
On comparing coefficients of $f_j, f'_j, \dots, f^{(4)}_j$, we get 5 equations in 5 variables and order of accuracy in Taylor series is 5. If we take any other set of 5 equations, we get order of accuracy in Taylor series lower than 5. Thus, to get the best order of accuracy, the following equations must be true.

\begin{align}
a+b+c+d+e &=0\\
h(2a+b-d-2e) &=1\\
4a+b+d+4e &=0\\
8a+b-d-8e &=0\\
16a+b+d+16e &=0
\end{align}

On solving these set of equations, we get the values of $(a,b,c,d,e)$ as:

\begin{equation}
(a,b,c,d,e) = \left(-\frac{1}{12h}, \frac{2}{3h}, 0 , -\frac{2}{3h}, \frac{1}{12h} \right)
\end{equation}

Therefore the finite difference approximation with 4th order accuracy is:
\begin{equation}
f'_j = \frac{1}{12h}(-f_{j+2}+8f_{j+1}-8f_{j-1}+f_{j-2}) + \mathcal{O}(h^4)
\end{equation}

<!-- # Blocks -->

<!-- ## Equations -->

<!-- Here is an equation. -->

<!-- \begin{equation}  -->
<!--   f\left(k\right) = \binom{n}{k} p^k\left(1-p\right)^{n-k} -->
<!--   (\#eq:binom) -->
<!-- \end{equation}  -->

<!-- You may refer to using `\@ref(eq:binom)`, like see Equation \@ref(eq:binom). -->


<!-- ## Theorems and proofs -->

<!-- Labeled theorems can be referenced in text using `\@ref(thm:tri)`, for example, check out this smart theorem \@ref(thm:tri). -->

<!-- ::: {.theorem #tri} -->
<!-- For a right triangle, if $c$ denotes the *length* of the hypotenuse -->
<!-- and $a$ and $b$ denote the lengths of the **other** two sides, we have -->
<!-- $$a^2 + b^2 = c^2$$ -->
<!-- ::: -->

<!-- Read more here <https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html>. -->

<!-- ## Callout blocks -->


<!-- The R Markdown Cookbook provides more help on how to use custom blocks to design your own callouts: https://bookdown.org/yihui/rmarkdown-cookbook/custom-blocks.html -->
