# Solving Ordinary Differential Equations Numerically

## Introduction

As seen in the previous chapter, our main focus in this course is to solve ODEs i.e., 1 independent variable per dependent variable numerically.

**Initial Value Problem(IVP):** ODE along with boundary conditions at a single point. Typically, independent variable is time. 

Example:- 
\begin{equation}
    \frac{d^2\theta}{dt^2}+C\frac{d\theta}{dt}+\frac{g}{l}\sin \theta = 0
\end{equation}
with "initial conditions" given by $\theta(t=0)= \theta_0$ and $\frac{d\theta}{dt}(t=0) = 0$. 

**Boundary Value Problem(BVP):** Conditions known at multiple points
Example:- 
\begin{equation}
    \frac{d^2\theta}{dt^2}+C\frac{d\theta}{dt}+\frac{g}{l}\sin \theta = 0
\end{equation}
with "initial conditions" given by $\theta(t=0)= \theta_0$ and $\theta(t=1) = 0$.

Note that the above ODE is 2nd order, non-linear and homogeneous ODE. If an external forcing is given, then the equation becomes non-homogeneous.

We can convert the above second order ODE to a set of 2 first order ODEs.

Define $$\omega = \frac{d\theta}{dt}$$

Therefore equation() can be written as:
$$\frac{d\omega}{dt}+C \omega+\frac{g}{l}\sin \theta = 0$$
Therefore, equation() can be written as a system of 1st order ODEs as:
\begin{equation}
\begin{bmatrix} \dot{\theta} \\  \dot{\omega} \end{bmatrix}=\begin{bmatrix} \omega \\  -C \omega-\frac{g}{l}\sin \theta \end{bmatrix}
\end{equation}

with initial conditions as 
\begin{equation}
\begin{bmatrix} \theta(0) \\  \omega(0) \end{bmatrix}=\begin{bmatrix} \theta_0 \\  0 \end{bmatrix}
\end{equation}

Similarly, we can express any $n$th order ODE as system of $n$ 1st order ODEs. 

Hence, we'll first look into solving a first order ODE numerically and then solve Simple Pendulum equation numerically.


## Different Basic Methods

Consider solving the IVP
\begin{equation}
\frac{dy}{dt} = \sin(\exp(y^2)t)
\end{equation}
with the initial condition $y(0) = 1$. We can see that the analytical solution is not possible. To solve the IVP numerically, let us first discretise time as $\{t_k\}_{k=0}^n$ where $t_0 = 0$ and $t_n=T$ time at which we are interested in finding $y$ value and $y_{i+1}-y_i = \Delta t$ for $i\in\{0,1,\dots,n-1\}$.

**ATTACH GRID DISCRETISATION PIC**

We can find derivative $\frac{dy}{dt}$ at $t=t_i$(for all $i$), using a finite difference formula and then convert the differential equation to a set of algebraic equations. Solving these would give $y_i = y(t_i)$.

Forward difference gives: 
\begin{equation}
\frac{dy}{dt}|_{t_i}\approx \frac{y_{i+1}-y_i}{\Delta t} = \sin(\exp(y_i^2)t_i)
\end{equation}
for $i\in\{0,1,\cdots, n-1\}$

For $i=0$, we have:
\begin{equation}
y_1 = y_0 +\Delta t \sin(\exp(y_i^2)t_i)
\end{equation}
$y_1$ is easier to compute as $y_0 = y(t=0)$ is known. And hence $y_2$ can be computed and so on. 

Backward difference gives:
\begin{equation}
\frac{dy}{dt}|_{t_i}\approx \frac{y_{i}-y_{i-1}}{\Delta t} = \sin(\exp(y_i^2)t_i)
\end{equation}
for $i\in\{1,2, \cdots,n\}$
For $i=1$, we have:
\begin{equation}
y_1 = y_0 +\Delta t \sin(\exp(y_1^2)t_1)
\end{equation}
Given $y_0$, $y_1$ can be found by using the above equation. Note that it is not as trivial as that of Forward difference case here. To get $y_1$, we need to use some root finding algorithm. Similarly to get $y_{i+1}$, we need to invoke root finding Algorithm. But in the case of Forward difference(also known as **Forward Euler Scheme**), we need not invoke any Root Finding Algorithm to find $y_{i+1}$ and hence it is an **Explicit Scheme**

Backward Difference scheme is also referred to as  **Backward Euler Scheme**. This is an **Implicit Scheme**




## Linear Stability Analysis

Forward Euler seems to be more attractive because of the ease to compute the solution. But can we use this to solve all ODEs accurately? 

Consider the ODE $$\frac{dy}{dt} = f(y,t); \ \ \ y(t=0)=y_0$$
Forward difference gives:
\begin{equation}
y_{i+1}-y_i = \Delta t f(y_i,t_i)
\end{equation}

We need to make sure that the difference between the numerically obtained solution and the exact solution i.e., $y_i-y(t_i)$ is small i.e., $$\lim_{\Delta t \to 0}y_i -y(t_i) = 0$$ If $y(t)$ is bounded then $y_i$ has to be bounded.



Consider the example problem:
$$\frac{dy}{dt} = -2y; \ \ \ y(t=0)=1$$
The exact solution is $y(t) = \exp(-2t)$ which is bounded. 

Using Forward Euler, we get:
\begin{equation}
y_{i+1} -y_i = -2\Delta t y_i \implies y_{i+1}=(1-2\Delta t) y_i
\end{equation}

\begin{equation}
\implies y_{i+1} = (1-2\Delta t)^n y_0 = (1-2\Delta t)^n
\end{equation}

Consider $\Delta t = 2$, we get $y_n = (-3)^n y_0$ which is unbounded i.e., $\lim_{n\to \infty} y_n$ does not exist. Therefore, Forward Euler is bad for this $\Delta t$

## Accuracy

## Simple Pendulum - Solving System of ODEs

## Simple Pendulum - Finite difference for 2nd order derivative







<!-- # Sharing your book -->

<!-- ## Publishing -->

<!-- HTML books can be published online, see: https://bookdown.org/yihui/bookdown/publishing.html -->

<!-- ## 404 pages -->

<!-- By default, users will be directed to a 404 page if they try to access a webpage that cannot be found. If you'd like to customize your 404 page instead of using the default, you may add either a `_404.Rmd` or `_404.md` file to your project root and use code and/or Markdown syntax. -->

<!-- ## Metadata for sharing -->

<!-- Bookdown HTML books will provide HTML metadata for social sharing on platforms like Twitter, Facebook, and LinkedIn, using information you provide in the `index.Rmd` YAML. To setup, set the `url` for your book and the path to your `cover-image` file. Your book's `title` and `description` are also used. -->



<!-- This `gitbook` uses the same social sharing data across all chapters in your book- all links shared will look the same. -->

<!-- Specify your book's source repository on GitHub using the `edit` key under the configuration options in the `_output.yml` file, which allows users to suggest an edit by linking to a chapter's source file.  -->

<!-- Read more about the features of this output format here: -->

<!-- https://pkgs.rstudio.com/bookdown/reference/gitbook.html -->

<!-- Or use: -->

<!-- ```{r eval=FALSE} -->
<!-- ?bookdown::gitbook -->
<!-- ``` -->


